### PR TITLE
Trades model test

### PR DESCRIPTION
**Pull request by MoyasiGinko**
### In this milestone,

- Created a new branch `trades-model-test`
- Setup the `trade_spec.rb` file
- Added tests for validations and associations

### Test results:
image

### CODE REVIEW

**Review by lincoln1883 — CHANGES_REQUESTED** [review]
# Hi @MoyasiGinko , 👋🏻👋🏻

Great job so far! 💯🤩🚀
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No Linters error ✨
- Followed Gitflow 🔥
- Great for writing unit tests, all passed ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lincoln1883** [comment]
Though there are no obvious issues with your tests, great job there. As was mentioned in the previous PR to avoid issues in the development branch, kindly update your branch locally by merging development into it resolving the conflicts then push the updated branch in the PR.

**Comment by MoyasiGinko** [comment]
is it really necessary though? anyways, pulled the changes from the development and updated the branch. awaiting for your review, please.

**Review by lincoln1883 — APPROVED** [review]
Hello @MoyasiGinko, 
Great job implementing the changes there is nothing else to say it's time to merge.

**Pull request merged**
